@Metadata.allowExtensions: true
@EndUserText.label: '###GENERATED Core Data Service Entity'
@AccessControl.authorizationCheck: #CHECK
define view entity ZC_TRMIS_ASSET_VAL000
  
  as projection on ZR_TRMIS_ASSET_VAL000
{
  key AssetUuid,
  key AssetValue,
  AssetValueExternal,
  AmountOfInterest,
  AmountOfInterestChangeAmt,
  ApmmInsuredValue,
  AssetCategory,
  AssetStatus,
  AssetValueFormula,
  AssetValueOnl,
  AssetValue100Percent,
  AssetVal100PercntChngAmt,
  AssetValueChangeAmount,
  AssetValueForInterest,
  AssetValForInterestchngAmt,
  AssetName,
  AssetValueStatus,
  BusinessInterruption,
  BusinessInterruptionChngAmt,
  BusinessUnit,
  CargoValue,
  ContentEquipment,
  CranesAndHandlingEquipment,
  CranesHandlingEquipChngAmt,
  Createdb,
  Currency,
  CurrencyCode,
  DeadweightTonnage,
  DeclaredValue,
  Deductible,
  Equipment,
  Flag,
  FlagId,
  GrossTonnage,
  Hierarchy,
  HullValue,
  HullValueChangeAmount,
  Infrastructure,
  Lastmodifiedb,
  MostRecent,
  RkNextPtr,
  OtliValue,
  OtliValueChangeAmount,
  HierarchyNode,
  OwnerId,
  PIClubNew,
  PIClub,
  RkPrevPtr,
  PropHandlingEquipChngAmt,
  Property,
  PropertyAndHandlingEquip,
  PropertyChangeAmount,
  PvSTOnly,
  Recordtyp,
  RenewalAssignment,
  Revenue,
  RkErrorDetail,
  RkErrorFlag,
  RkGenAssetValuesPid,
  RkPendingVoidCount,
  RkPidConstructor,
  Status,
  TotalInsuredValue,
  TotalInsuredValueChngAmt,
  Utilisation,
  Utilization,
  UtilizationChangeAmount,
  ValuationDate,
  ValuationEndDate,
  VarianceNotes,
  VolumeTons,
  WarValue,
  WarValueChangeAmount,
  WarehouseOfficeBuildings,
  Createdby,
  Createdat,
  Lastchangedby,
  Lastchangedat,
  _Asset: redirected to parent ZC_TRMIS_ASSET000
  
}
